// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['Bridge']['OpenDirectoryDialog'](arg1);
}
